// api/replicateApi.ts
import axios from 'axios';

export const generateOutfitImage = async (prompt: string) => {
  const replicateApiUrl = 'https://api.replicate.com/v1/predictions';
  const replicateModel = 'stability-ai/stable-diffusion';
  const replicateApiKey = process.env.NEXT_PUBLIC_REPLICATE_API_KEY; // Set your API key in environment variables

  const response = await axios.post(
    replicateApiUrl,
    {
      version: 'YOUR_MODEL_VERSION', // Replace with the Stable Diffusion model version
      input: {
        prompt,
      },
    },
    {
      headers: {
        Authorization: `Token ${replicateApiKey}`,
        'Content-Type': 'application/json',
      },
    }
  );

  return response.data.output; // This returns the image URL generated by Stable Diffusion
};
